server:
  port: 8001

mybatis:
  config-location: classpath:SqlMapConfig.xml
  type-aliases-package: micro.service.cloud.entity
  mapper-locations: classpath:mapper/*.xml

spring:
  application:
    # 注册到Eureka的服务名
    name: ms-cloud-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://127.0.0.1:3306/micro_service?useUnicode=true&characterEncoding=UTF-8&useTimezone=true&serverTimezone=Asia/Shanghai
    username: root
    password: root
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 200

eureka:
  client:
    service-url:
      #Eureka单机配置
      defaultZone: http://eureka7001.com:7001/eureka
      #Eureka集群配置
#      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka
  instance:
    #eureka客户端id
    instance-id: ms-cloud-dept-8001
    #访问路径可以显示IP地址
    prefer-ip-address: true
# 自定义微服务介绍信息
info:
  author: 一花一世界，一叶一菩提
  build-version: @project.version@
  email: my-email@163.com
  company: my-company